name: "Events README"
description: "🗓 Generate a README.md summary for your events repository"
author: "Anand Chowdhary <https://github.com/AnandChowdhary>"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  token:
    required: true
    description: "GitHub token"
branding:
  icon: "calendar"
  color: "green"
