name: "Notes Summary README"
description: "🗒️ Generate a README.md summary for your notes repository"
author: "Anand Chowdhary <https://github.com/AnandChowdhary>"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  token:
    required: true
    description: "GitHub token"
  commitMessage:
    required: false
    description: "Commit message"
  directory:
    required: true
    description: "Directory name"
  caption:
    required: false
    description: "JavaScript function to generate caption"
  openAiApiKey:
    required: false
    description: "OpenAI API key used to generate emojis"
  openAiModel:
    required: false
    description: "OpenAI model to use for emoji generation"
    default: "gpt-4.1-mini"
branding:
  icon: "calendar"
  color: "green"
