import { getInput, setFailed, setOutput } from "@actions/core";
import { execSync } from "child_process";
import { readdir, readFile, writeFile } from "fs-extra";
import markdownToTxt from "markdown-to-txt";
import { join } from "path";
import { format } from "prettier";
import truncate from "truncate-sentences";
import frontMatter from "front-matter";

interface Item {
  slug: string;
  path: string;
  source: string;
  title?: string;
  excerpt?: string;
  date: Date;
  attributes?: Record<string, unknown>;
}

/**
 * Get a item from a file
 * @param dirName - The directory where the file resides
 * @param year - The year of the item
 * @param file - The file name
 * @returns Parsed item
 */
const parseItemFile = async (dirName: string, year: string, file: string): Promise<Item> => {
  const path = join(".", dirName, year, file);
  const source = `https://github.com/${process.env.GITHUB_REPOSITORY}/blob/${process.env.GITHUB_REF_NAME}/${path}`;
  const contents = await readFile(path, "utf8");
  const { attributes, body } = frontMatter<{
    date?: unknown;
    title?: unknown;
    excerpt?: unknown;
    description?: unknown;
    summary?: unknown;
  }>(contents);

  const date: Date =
    "date" in attributes && typeof attributes.date === "string"
      ? new Date(attributes.date)
      : "date" in attributes && typeof attributes.date === "number"
      ? // Arbitiary rule to differentiate ms timestamp from year
        attributes.date < 3000
        ? new Date(`${attributes.date}-01-01`)
        : new Date(attributes.date)
      : "date" in attributes && attributes.date instanceof Date
      ? attributes.date
      : // Use git file creation date if no date is specified
        new Date(
          execSync(`git log --format=%aD ${dirName}/${year}/${file} | tail -1`).toString().trim()
        );

  const title = (
    "title" in attributes && typeof attributes.title === "string"
      ? attributes.title
      : body.match(/^# (.*)/m)?.[1]
  )?.trim();
  if (!title) throw new Error(`Unable to parse title in ${path}`);

  const excerpt =
    "excerpt" in attributes && typeof attributes.excerpt === "string"
      ? attributes.excerpt
      : "description" in attributes && typeof attributes.description === "string"
      ? attributes.description
      : "summary" in attributes && typeof attributes.summary === "string"
      ? attributes.summary
      : body.indexOf(title) > -1
      ? body.substring(body.indexOf(title) + title.length)?.trim() ?? body.trim()
      : body.trim();

  return {
    slug: file,
    path,
    source,
    title: title,
    date,
    excerpt: excerpt ? truncate(markdownToTxt(excerpt), 500) : undefined,
    attributes,
  };
};

const token = getInput("token") || process.env.GH_PAT || process.env.GITHUB_TOKEN;

export const run = async () => {
  if (!token) throw new Error("GitHub token not found");
  const dirName = getInput("dirName");
  const commitMessage = getInput("commitMessage") || `:pencil: Update ${dirName} summary [skip ci]`;
  const commitEmail =
    getInput("commitEmail") || "41898282+github-actions[bot]@users.noreply.github.com";
  const commitUsername = getInput("commitUsername") || "github-actions[bot]";

  const allItems: { [index: string]: Array<Item> } = {};
  let totalItems = 0;
  let pastItems = "";
  let upcomingItems = "";
  const years = await readdir(join(".", dirName));
  for await (const year of years) {
    const items = await readdir(join(".", dirName, year));
    for await (const item of items) {
      totalItems++;
      allItems[year] = allItems[year] || [];
      const itemFile = await parseItemFile(dirName, year, item);
      allItems[year].push(itemFile);
    }
  }
  Object.keys(allItems)
    .sort((a, b) => parseInt(b) - parseInt(a))
    .forEach((year) => {
      allItems[year] = allItems[year].sort(
        (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
      );
      let addedYears: Array<string> = [];
      allItems[year].forEach((item) => {
        const isPast = new Date(item.date).getTime() < new Date().getTime();
        const text = `${addedYears.includes(year) ? "" : `### ${year}\n\n`}- [${
          item.title || `\`${item.slug}\``
        }](./${dirName}/${year}/${item.slug})\n`;
        if (isPast) pastItems += text;
        else upcomingItems += text;
        addedYears.push(year);
      });
    });
  let content = `## 🌯 Summary
- ${totalItems} ${dirName} in ${years.length} years
`;
  if (upcomingItems.length) content += upcomingItems;
  if (pastItems.length) content += pastItems;
  const originalReadmeContents = format(await readFile(join(".", "README.md"), "utf-8"), {
    parser: "markdown",
  });
  await writeFile(
    join(".", "README.md"),
    format(
      `${
        originalReadmeContents.split("<!--autogenerated-->")[0]
      }<!--autogenerated-->\n\n${content.trim()}\n<!--/autogenerated-->${
        originalReadmeContents.split("<!--/autogenerated-->")[1]
      }`,
      { parser: "markdown" }
    )
  );
  await writeFile(
    join(".", "api.json"),
    JSON.stringify(
      Object.values(allItems)
        .flat()
        .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()),
      null,
      2
    ) + "\n"
  );
  try {
    execSync(`git config --global user.email "${commitEmail}"`, {
      stdio: "inherit",
    });
    execSync(`git config --global user.name "${commitUsername}"`, {
      stdio: "inherit",
    });
    execSync("git pull", { stdio: "inherit" });
    execSync(`git diff --quiet && git diff --staged --quiet || git commit -am "${commitMessage}"`, {
      stdio: "inherit",
    });
    execSync("git push", { stdio: "inherit" });
  } catch (error) {
    console.error(String(error));
    throw new Error(error as any);
  }
  setOutput("number-of-items", totalItems);
};

run().catch((error) => {
  console.error("ERROR", error);
  setFailed(error.message);
});
