name: Dependabot PR CI
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  label-approve:
    name: Label and approve minor/patch updates
    runs-on: ubuntu-18.04
    steps:
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          approve-minor: true
          approve-patch: true
          auto-label: true
